version: '3.8'

services:
  web:
    build: ./frontend
    ports:
      - 3003:80
    volumes:
      - ./frontend:/app
  api:
    build: ./backend
    ports:
      - 2000:2000
    env_file:
      - ./env.sh
    volumes:
      - ./backend:/app
  db:
    image: mongo:4.0-xenial
    ports:
      - 27018:27017
    volumes:
      - order:/data/db

volumes:
  order:
